application: cody-static-sites
version: 1
runtime: python
api_version: 1

handlers:
- url: /corbyhaas
  static_files: corbyhaas/index.html
  upload: corbyhaas/index.html

- url: /corbyhaas
  static_dir: corbyhaas
